---
name: Lint Actions

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main, development]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running pdxhub actionslint for branch ${{ github.ref_name }}"
      - uses: actions/checkout@v4
      - name: Actions Lint
        uses: raven-actions/actionlint@v2
